---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
  labels:
    app.kubernetes.io/name: subscription-service
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: subscription-service
spec:
  template:
    metadata:
      annotations:
#        autoscaling.knative.dev/min-scale: "1"
        sidecar.istio.io/inject: 'true'
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app.kubernetes.io/name: subscription-service
        app.kubernetes.io/version: 1.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger-collector.istio-system.svc:4317/api/traces
            - name: POSTGRES_HOST
              value: newsletter-postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgrespass
                  name: newsletter-postgres
          image: quay.io/uegozi/serverless-workflow-newsletter-subscription-service:2.2-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: subscription-service
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
