---
apiVersion: v1
kind: Secret
metadata:
  name: newsletter-postgres
data:
  postgrespass: cGFzcwo=
type: Opaque
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display@sha256:a214514d6ba674d7393ec8448dd272472b2956207acb3f83152d3071f0ab1911
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: newsletter-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: newsletter-postgres
  type: ClusterIP
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: e33376813365d4d2d345ce871768a7f7ca700ff4
    app.quarkus.io/build-timestamp: 2022-09-07 - 10:50:11 +0000
  labels:
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/name: subscription-flow
  name: subscription-flow
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 1.0-SNAPSHOT
        app.kubernetes.io/name: subscription-flow
    spec:
      containers:
        - env:
            - name: POSTGRES_HOST
              value: newsletter-postgres
            - name: SUBSCRIPTION_API_URL
              value: http://subscription-service.newsletter-showcase.svc.cluster.local
          image: quay.io/uegozi/serverless-workflow-newsletter-subscription-flow:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: subscription-flow
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsletter-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsletter-postgres
  template:
    metadata:
      labels:
        app: newsletter-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgrespass
                  name: newsletter-postgres
          image: postgres:13.4-alpine3.14
          imagePullPolicy: IfNotPresent
          name: newsletter-postgres
          ports:
            - containerPort: 5432
              name: tcp
              protocol: TCP
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-display-trigger
spec:
  broker: default
  filter:
    attributes:
      type: new.subscription
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
